### ISSUE TITLE
How to add prompt settings to Google OAuth?

### ISSUE THREAD

**Issue by justinforlenza** [mironal/electron-oauth-helper#84]
I am attempting to add the Google OAuth "prompt" parameter so that a user is asked to choose an account even if there is only one, giving them the option to enter a new account. 

I added "prompt" into my config object however the OAuth2Provider appears to just ignore it. 

Google Documentation on Additional Parameters:

https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters

**Comment by strotmann** [comment]
// Your can use custom parameter.
provider.on("before-authorize-request", parameter => {
    parameter["XXXX-Hoge"] = "hogehoge"
})
