### ISSUE TITLE
Throw error in electron@7.1.2

### ISSUE THREAD

**Issue by ghost** [mironal/electron-oauth-helper#85]
![Screenshot from 2020-01-18 15-19-06](https://user-images.githubusercontent.com/26399261/72661900-fd787980-3a05-11ea-8a51-a32723cc1393.png)
After generating code, so access token can't be generated. Works in electron@5.x.x

**Comment by pranavwani** [comment]
@mironal this issue related to the https://github.com/mironal/electron-oauth-helper/pull/86 PR, which was solved. You can close now.

**Comment by mironal** [comment]
@pranavwani Thanks!
