### ISSUE TITLE
v5.0.2  can't install

### ISSUE THREAD

**Issue by pranavwani** [mironal/electron-oauth-helper#88]
Thank's @mironal for updating dependency

But it throw's error while installing(Tried to install using `npm` and `yarn`)

![Screenshot from 2020-01-25 15-04-17](https://user-images.githubusercontent.com/60286761/73119179-03c9a100-3f84-11ea-9a04-da6caa1c4cab.png)

**Comment by mironal** [comment]
Thanks for your report.

I fixed the issue and released v5.0.3.
