### ISSUE TITLE
Facing issue in v5.1.0

### ISSUE THREAD

**Issue by pranavwani** [mironal/electron-oauth-helper#96]
**Description:** @mironal Please check last [PR](https://github.com/mironal/electron-oauth-helper/pull/95) code was not found in the latest release.

Can you please re-publish the package with the latest code on npm

**Comment by mironal** [comment]
Sorry. I just published v5.1.1.  Can you try to see if it was published correctly?

**Comment by pranavwani** [comment]
Hi, @mironal it's done. Thank :+1:

**Comment by pranavwani** [comment]
Closing the issue
